# Generated by Django 5.1.1 on 2025-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxleLoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_unit', models.CharField(max_length=5)),
                ('allowable_mass', models.FloatField()),
                ('actual_mass', models.FloatField()),
                ('no_of_axles', models.IntegerField()),
                ('axle_type', models.CharField(max_length=20)),
                ('w_spc_a', models.FloatField()),
                ('w_spc_b', models.FloatField()),
                ('type_pressure', models.FloatField()),
                ('total_mass', models.FloatField()),
                ('wheel_track', models.FloatField()),
                ('av_no', models.CharField(max_length=10)),
                ('laden_length', models.FloatField()),
                ('laden_width', models.FloatField()),
                ('laden_height', models.FloatField()),
                ('total_distance', models.FloatField()),
                ('distance_escorted', models.FloatField()),
                ('no_of_escorts', models.IntegerField()),
                ('rural_speed', models.FloatField()),
                ('engineer_fee', models.BooleanField(default=False)),
                ('weekend_travel', models.BooleanField(default=False)),
                ('mobile_crane', models.BooleanField(default=False)),
                ('province', models.CharField(max_length=2)),
                ('calculated_fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
