# Generated by Django 5.1.1 on 2025-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbFinYear', models.IntegerField()),
                ('dbConstName', models.CharField(max_length=100)),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbConstValue', models.FloatField()),
            ],
        ),
    ]
