# Generated by Django 5.1.1 on 2025-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_constant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
